# Spring Application Name
spring.application.name=fincaapi

# Database
spring.datasource.url=jdbc:postgresql://ep-autumn-term-apc359jj.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_L6akMQlhE2wV
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Naming Strategy
spring.jpa.hibernate.naming.physical-strategy=com.finca.api.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Server
server.port=${PORT:8091}
